### ISSUE TITLE
What is the "compose" key ?

### ISSUE THREAD

**Issue by nicobo** [tuxedocomputers/tuxedo-keyboard#196]
I have an InfinityBook S15 with FR keyboard layout and default Tuxedo OS with Gnome.

Gnome preferences say the "Compose key" is set to "Layout default", so I'm supposed to be able to type **subscript** characters with the following keys combination : `<Compose> + _ + <character>` (there's a similar shortcut for superscript)

Example : `H₂O`

When I force it to a specific key it works, but I'm unable to detect which key is mapped to the "Compose key" **by default**.

What is the default vendor behavior ? Is there a default mapping or must I force it myself ?

**Comment by Darael** [comment]
If you are using one of the standard layouts, compose is usually unmapped, and you'll want to choose one of the options to put it on a key from the GNOME preferences. If you're on an ISO-style rather than ANSI-style physical keyboard, I recommend the "less/greater" option (xkb option compose:102), since you have the characters normally found on that key available as shift+comma and full stop.
